from bilanco import *
print('Aktif hesaplama')
x=input('Kasa hesabını giriniz:')
y=input('Alınan çek hesabını giriniz:')
z=input('Bankalar hesabını giriniz:')
c=input('Alicak senetler hesabını giriniz:')
k=input('Ticari mallar hesabını giriniz:')
a=input('Binalar hesabını giriniz:')
b=input('Taşıtlar hesabını giriniz:')
d=input('Demirbaşlar hesabını giriniz:')
aktifHesapla(x,y,z,c,k,a,b,d)
print('Pasif hesaplama')
q=input('Kısa vadelibanka kredi hesabını giriniz:')
w=input('Saticilar hesabını giriniz:')
e=input('Uzun vadeli banka kredi hesabnınıgiriniz:')
r=input('Borç senetleri hesabını giriniz:')
t=input('Sermaye hesabnı giriniz:')
pasifHesapla(q,w,e,r,t)
bilancoHesapla()
